config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'postcode_checker#index'
  get 'postcode_checker/validate', to: 'postcode_checker#validate'

  resources :whitelisted_postcodes
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/whitelisted_postcode.rb
# frozen_string_literal: true

class WhitelistedPostcode < ApplicationRecord
  before_validation :normalise_postcode
  validates :postcode, presence: true, uniqueness: true

  def normalise_postcode
    self.postcode = postcode.gsub(' ', '').downcase
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/postcode_checker_controller.rb
# frozen_string_literal: true

class PostcodeCheckerController < ApplicationController
  def validate
    flash[:notice] = if PostcodeValidator.new(params[:postcode]).valid?
                       'Great news, this postcode is in our service area'
                     else
                       "Unfortunately we couldn't find this postcode in our service area"
                     end
    render :index
  end
end

app/controllers/whitelisted_postcodes_controller.rb
# frozen_string_literal: true

class WhitelistedPostcodesController < ApplicationController
  before_action :find_whitelisted_postcode, only: %i[edit update destroy]

  def index
    @whitelisted_postcodes = WhitelistedPostcode.all.order(:postcode)
  end

  def create
    @whitelisted_postcode = WhitelistedPostcode.new(whitelisted_postcode_params)
    if @whitelisted_postcode.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def update
    if @whitelisted_postcode.update(whitelisted_postcode_params)
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    @whitelisted_postcode.destroy
    redirect_to whitelisted_postcodes_path
  end

  private

  def whitelisted_postcode_params
    params.require(:whitelisted_postcode).permit(:postcode)
  end

  def find_whitelisted_postcode
    @whitelisted_postcode = WhitelistedPostcode.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostcodeChecker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <%= yield %>

    <p><%= link_to 'Check a postcode', root_path %></p>
    <p><%= link_to 'Whitelisted postcodes', whitelisted_postcodes_path %></p>

  </body>
</html>

app/views/postcode_checker/index.html.erb
<h1>Postcode Checker</h1>

<%= form_tag(postcode_checker_validate_path, method: :get) do %>
  <%= label_tag(:postcode, 'Postcode:') %>
  <%= text_field_tag(:postcode, params[:postcode]) %>
  <br><br>
  <%= submit_tag('Check postcode') %>
  <br><br>
<% end %>

app/views/whitelisted_postcodes/edit.html.erb
<h1>Edit whitelisted postcode</h1>

<% if @whitelisted_postcode.errors.present? %>
  <%= @whitelisted_postcode.errors.full_messages.join(", ") %>
<% end %>

<%= form_with model: @whitelisted_postcode, local: true do |form| %>
  <p>
    <%= form.label :postcode, 'Postcode:' %>
    <%= form.text_field :postcode %>
  </p>
  <p>
    <%= form.submit 'Edit postcode' %>
  </p>
<% end %>

<p><%= link_to 'View whitelisted postcodes', whitelisted_postcodes_path %></p>

app/views/whitelisted_postcodes/index.html.erb
<h1>Whitelisted postcodes</h1>

<table>
  <thead>
    <th>Postcode</th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <% @whitelisted_postcodes.each do |whitelisted_postcode| %>
      <tr>
        <td><%= whitelisted_postcode.postcode %></td>
        <td><%= link_to 'Edit', edit_whitelisted_postcode_path(whitelisted_postcode) %></td>
        <td><%= link_to 'Delete', whitelisted_postcode_path(whitelisted_postcode), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'Add new postcode', new_whitelisted_postcode_path %></p>

app/views/whitelisted_postcodes/new.html.erb
<h1>Add to the postcode whitelist</h1>

<% if @whitelisted_postcode && @whitelisted_postcode.errors.present? %>
  <%= @whitelisted_postcode.errors.full_messages.join(", ") %>
<% end %>

<%= form_with scope: :whitelisted_postcode, url: whitelisted_postcodes_path, local: true do |form| %>
  <p>
    <%= form.label :postcode, 'Postcode:' %>
    <%= form.text_field :postcode %>
  </p>
  <p>
    <%= form.submit 'Add new postcode' %>
  </p>
<% end %>

<p><%= link_to 'View whitelisted postcodes', whitelisted_postcodes_path %></p>